apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: healthcare
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "auth"
        static_configs:
          - targets: ["auth.healthcare.svc.cluster.local:8000"]

      - job_name: "patient"
        static_configs:
          - targets: ["patient.healthcare.svc.cluster.local:8000"]

      - job_name: "appointment"
        static_configs:
          - targets: ["appointment.healthcare.svc.cluster.local:8000"]

      - job_name: "clinical-notes"
        static_configs:
          - targets: ["clinical-notes.healthcare.svc.cluster.local:8000"]

      - job_name: "billing"
        static_configs:
          - targets: ["billing.healthcare.svc.cluster.local:8000"]
