apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  namespace: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: graduation-project-billing:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: billing-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: billing-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: billing-secret
                  key: JWT_SECRET
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: billing-secret
                  key: RABBITMQ_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
