global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "auth"
    static_configs:
      - targets: ["auth:8000"]

  - job_name: "patient"
    static_configs:
      - targets: ["patient:8000"]

  - job_name: "appointment"
    static_configs:
      - targets: ["appointment:8000"]

  - job_name: "clinical-notes"
    static_configs:
      - targets: ["clinical-notes:8000"]

  - job_name: "billing"
    static_configs:
      - targets: ["billing:8000"]
